name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  First:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.urmum }}
    steps:
      - run: echo $AWS_KEY
      - uses: actions/checkout@v2
      - run: terraform init
      - run: terraform plan -var access_key=$AWS_KEY
