name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  First:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.urmum }}
    - run: echo ${{ AWS_KEY }}
    - run: terraform init
    - run: terraform plan
    continue-on-error: true
    