name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  First:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.urmum }}
    steps:
      - run: echo "fergt"
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -la ./../../_temp
      - run: ls -la ./../
      - run: terraform init
      - run: terraform plan
